version: "3.7"

services:
  sqldb-2022:
    container_name: sqldb-2022
    build:
      context: ./
      dockerfile: ./Dockerfile-sql
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"

  client-app:
    container_name: client-app
    build:
      context: ./
      dockerfile: ./Dockerfile-client
    tty: true
